version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reportingplatform
    volumes:
      - type: bind
        source: ./pgdata
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
    ports:
      - 5432:5432
