import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { version } from "../package.json";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Hello next
        <button className="bg-red-300 p-2 m-2 rounded">{version}</button>
      </main>
    </>
  );
}
