import LoadingWrapper from "@/components/LoadingWrapper";
import PostCard from "@/components/PostCard";
import useAxios from "axios-hooks";
import Head from "next/head";
import Link from "next/link";
type Post = {
  id: string;
  title: string;
};

export default function Home() {
  const [{ data: users, loading }, refetchUsers] = useAxios<Post[]>(
    "api/post",
    { useCache: false }
  );

  function deleteUser(id: string) {
    console.log("delete this user");
    fetch(`api/user/${id}`, { method: "DELETE" })
      .then((res) => res.json())
      .then((res) => {
        console.log("deeted user");
        refetchUsers();
      });
  }

  return (
    <>
      <Head>
        <title>Advise Me - Posts </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h3>Posts</h3>
        <div className="p-5 grid grid-cols-5 gap-3">
          <LoadingWrapper isLoading={loading}>
            {users?.map((u) => {
              return <PostCard key={u.id} title={u.title} />;
            })}
          </LoadingWrapper>
        </div>
      </main>
    </>
  );
}
